### ISSUE TITLE
Execute/benchmark 5GTANGO package on vim-emu

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-benchmark#17]
Use vim-emu as target execution platform. Interact through LLCM, dockerd, collectd ...

Development branch: `dev`

Test target: `rdev`

Documentation done in **Bear**.

### TODOs
---
- [x] add pdriver structure
- [x] add `executor.py`
- [x] config file with target platform
- [x] Use a `tng-bench-emusrv` that offers REST and controls the emulator. Implemented in 
`server.py` in `pdrivers`
    - [x] start emulation `POST` -> in own process
    - [x] stop emulation `DELETE`
    - [x] integrate vim-emu into `server.py`
- [x] initial executor logic: run over all experiments, one by one
- [x] create emulation
- [x] upload service package
---
- [x] instantiate service
    - [x] have a first test service for real benchmarking (align it with our IETF work)
    - [x] check test service is correctly deployed by vim-emu LLCM
        - [x] only have data interface deployed (no mgmt for now)
        - [x] ensure correct IPs are assigned
            - [x] address to PED and gen service
            - [x] use address in vim-emu (get address attribute)
        - [x] ping test (fails! routes? bridge in VNF correct? needs debugging)
            - [x] routes? -> PASS
            - [x] ping to br0 works? -> FAIL
            - [x] chaining rules / switch configurations -> FAIL (this is the problem, see workaround)
                - Problem: chaining rules are not correctly applied by LLCM
            - [x] BUG: Ryu is not started: `curl 127.0.0.1:8080`
    - [x] have a first, small PED for as test experiment
---
- [x] perform experiment
    - [x] execute commands from PED inside MP containers (docker remote API?)
        - [x] start cmd and logging
        - [x] stop cmd and logging
    - [x] document MP container design and command execution [here](https://github.com/sonata-nfv/tng-sdk-benchmark/wiki/Probes-(measurement-points))
    - [x] wait experiment time before executing stop command
---
- [x] collect results
  - [x] collect file-based results (use `docker cp` and put all files in a output dir with experiment name)
     - see: https://docker-py.readthedocs.io/en/stable/containers.html?highlight=get_archive
     - have a default folder `/tngbench_share`
     - [x] `cmd_start.log` and `cmd_stop.log`
     - [x] collect arbitrary other files(?) how to define this(?) skip for now(?)
     - [x] collect `docker logs` output
  - [x] monitor container metrics during experiments
    - [x] collect docker stats during experiment
    - [x] write container metrics to files
  - [ ] build a more lightweight/complete monitoring of the entire test host (`collectd`?)
  - [ ] VnV probes will push to pushgateway (monitoring) to collect results. Can we also support this (wait for details of VnV design)?
---
- [ ] terminate service
- [x] destroy emulation
---
- [x] add `test executor machine setup manual` Markdown file to repo
   - [x] ansible-based test executor machine setup
   - [x] do a really, really good executer machine setup guide!!!
---
- [x] remove old `emulator.py`
- [ ] create a non-small ped for the suricate example
- [ ] write a guide on how to execute the suricata example
- [ ] clean up old examples (old example ped files, old example packages)

---
## vime-meu
All vim-emu changes are done in branch `tngbench` and should go directly to Gerrit!

---
## Next steps
Now that the service is deployed correctly, we need to get the experiment triggered and executed.

**Comment by mpeuster** [comment]
tng-bench CLI
```
tng-bench -p examples/peds/ped_suricata_tp_small.yml --no-execution
```

tng-bench-emusrv
```
sudo tng-bench-emusrv
```
tng-bench-emusrv API
```
curl -X POST http://fgcn-peuster.cs.upb.de:4999/api/v1/emulation
curl -X DELETE http://fgcn-peuster.cs.upb.de:4999/api/v1/emulation
curl -X GET http://fgcn-peuster.cs.upb.de:4999/api/v1/emulation
```

vim-emu 5GTANGO LLCM API
```
curl -X GET http://fgcn-peuster.cs.upb.de:5000/packages
curl -i -X POST -F package=@de.upb.ns-1vnf-ids-suricata.0.1.tgo http://fgcn-peuster.cs.upb.de:5000/packages
curl -X POST http://fgcn-peuster.cs.upb.de:5000/instantiations -d "{}"
```

**Comment by mpeuster** [comment]
Next step: Implement generic driver API and pass calls to vimemu driver:

* setup
* run
* teardown

**Comment by mpeuster** [comment]
Debugging MPs

```
docker exec mn.mp.input ls /tngbench_share
docker exec mn.mp.output ls /tngbench_share
docker exec mn.mp.input cat /tngbench_share/cmd_start.log
docker exec mn.mp.output cat /tngbench_share/cmd_start.log
```
