### ISSUE TITLE
IETF: Replicate Gym experiments using tng-bench for IETF input

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-benchmark#41]
See: https://github.com/raphaelvrosa/vnf-bench-model/tree/master/experiments/vnf-bench-01

---
Test PED: `tng-bench -p examples/peds/ped_suricata_test.yml -v`

- [x] install tango1 as test executor machine
- [x] build and use latest Suricata VNF
  - [x] add feature for different entrypoints to run it with different rulesets (overwrite `SON_EMU_CMD ` and `SON_EMU_CMD_STOP`: #42 )
- [x] test all using iperf probes
- [x] add tcpreplay probes as in Gym experiments
- [x] Monitoring (result collection) to VNF itself (`docker-vnfs/suricata-ids/suricata/stats.py`)
  - [x] PROBLEM: tng-bench needs to execute stop.sh in VNFs directly, so it happens BEFORE result collection. Sic!
  - [x] Fix: values are 0 `error f=0`
- [x] create a folder with PEDs, BDs, results (in vnf-bench-model repo)
  - `vnf-bench-model/experiments/upb-vnf-bench-01`
  - `tng-bench -p ped_suricata_experiment_small.yml -v`
- [x] build fresh PED files etc. in vnf-bench-model repo to do full experiment
  - [x] Add traffic counter dump script to MPs
  -  Gym experiment: https://github.com/raphaelvrosa/vnf-bench-model/commit/ecdf1014c749091c3bda66d9b08364e54164b168
  - [x] small PED
  - [x] full PED
- [x] ensure that VNF-BD is created correctly from PEDs
- [x] Add README.md to that folder an document what we did
---
- [x] do a first long running tests (see Bear.app) to check stability for real experiments
  - [x] 36
  - [x] 180
  - [x] 1800(~26h runtime, result folder ~323MB, *.tar.gz ~14MB)
- [ ] do the experiment (on tango5 machine (using rdev2 as ctrl?))
  - [x] define experiment to produce example results (see repo, 36 configs)
  - [x] fine tune times on target machine (tcpreplay)
  - [x] Bug: Suricata numbers in `results.yml` are often 0. Looks like this is a result processing problem only. (I checked the "emty" case where it is normal)
  - [x] ~~check if resource limits are applied correctly~~-> new issue #59
     - [x] ~~Bug: `cpuset` is ignored.~~ **confirmed** -> new issue #59
  - [x] kick-off execution 
  - [ ] increase repetitions
---
- [x] fix integration with latest vim-emu master (multi VDU support breaks tng-bench compatibility)
---
- [ ] ~~Result analysis? Jupyter?~~ -> new issue #60
---

### OpenBugs
- [x] network setup (E-LINE) seems to be broken by latest emulator LLCM developments
  - this is the root cause: https://github.com/sonata-nfv/son-emu/issues/292

**Comment by mpeuster** [comment]
https://github.com/raphaelvrosa/vnf-bench-model/pull/3

**Comment by mpeuster** [comment]
~~Private results archive: https://git.cs.upb.de/peuster/tng-bench-result-archive~~
Private results and experimentation: https://git.cs.upb.de/peuster/tng-bench-experiments
(to store even buggy results and not mess up this repo)
