### ISSUE TITLE
PED-based SON_EMU_CMD start commands

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-benchmark#42]
Allow custom `SON_EMU_CMD` properties in PED file. Overwrite the ENV when the VNF is started.

Needed for #41 

---
### Design

New PED format

```yaml
# additional containers for traffic generation/measurements (like SAPs)
    measurement_points:  # static MP definition and configuration; no dynamic parameter ranges here
      - name: "mp.output"
        connection_point: "ns:output"
        container: "mpeuster/tng-bench-mp"
        address: "20.0.0.254/24"  # address of the data interface of the MP
      - name: "mp.input"
        connection_point: "ns:input"
        container: "mpeuster/tng-bench-mp"
        address: "20.0.0.1/24"  # address of the data interface of the MP
    # resource configurations to be tested during profiling run (defined per VNF)
    experiment_parameters:  # renamed RLs; this is the only section with dynmaic ranges
      - function: "de.upb.ids-suricata.0.1"  # function also defines the type; we might have others, like - service:
        cmd_start: null # optional; vim-emu implementation easy; OSM might be a challange (cloud.init?)
        cmd_stop: null 
        cpu_bw: 0.5 #{min: 0.05, max: 0.15, step: 0.05}       
        cpu_cores: 1
        mem_max: [64]
        mem_swap_max: null
        io_bw: null
      - function: "mp.input"
        cmd_start: "iperf -c 20.0.0.254 -t 3"
        cmd_stop: "uptime"
        cpu_bw: 0.2
        cpu_cores: 1
        mem_max: 512
        mem_swap_max: null
        io_bw: null
      - function: "mp.output"
        cmd_start: ["iperf -s"]  # moved from MPs
        cmd_stop: "uptime"
        cpu_bw: 0.2
        cpu_cores: 1
        mem_max: 512
        mem_swap_max: null
        io_bw: null


```

For the VNFs, the VNFDs get the commands injected:

```yaml
- id: "vdu01"
    vm_image: "ubuntu:16.04"
    vm_image_format: "docker" 
    vm_cmd_start: "xxx"
    vm_cmd_stop: "yyy"
```

the 5GTANGO LLCM then needs to overwrite the environment variables of the containers.

---
### TODO

- [x] enable new PED format
- [x] update tests
- [x] run examples
  - [x] apply commands to MPs (through driver)
  - [x] apply commands to VNFs (through VNFDs?)
    - [x] add cmds to generated VNFDs
    - [x] change LLCM to overwrite ENVs of containers
- [x] update all example PEDs
- [x] check multi command generation
