### ISSUE TITLE
Prometheus data exporter

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-benchmark#56]
Use a Prometheus instance to collect benchmarking data (start with collecting time series data, then extend to parameters etc.)

This will replace the Docker stats poller and solve #72 

## TODOs

- [x] run prometheus in a Docker next to tng-bench
- [x] Data collection
  - [x] collect docker stats
  - [x] collect executer machine stats
  - [x] collect VNF-specific stats (implemented for Suricata)
  - [ ] collect probe results (skipped for now)
  - [ ] collect experiment parameters etc ((skipped for now, push-gw?)
- [x] disable docker stats poller
- [x]  update tng-sdk-benchmark wiki (to explain new collection and results)
- [x] let Prometheus write the data persistently (check how we can do this with docker-compose)
- [x] let tng-bench write out a file which stores the start / end timestamps of the experiments
- [x] configure experiment environment
- [x] DO EXPERIMENTS TO COLLECT DATA
- [x] let tng-bench automatically start/stop/configure the Prometheus instance upon experiment execution --> move to dedicated issue
- [x] let tng-bench automatically archive/export the Prometheus data for sharing to another Prometheus instance
- [ ] ~~automate setup and installation using the ansible installer?~~ manually for now
- [x] document everything: [see here](https://github.com/sonata-nfv/tng-sdk-benchmark/wiki/Using-Prometheus)

---
## Environments:

* Dev: mapupb -> rdev
* Experiment: rdev2 -> tango5
---

## Tool Overview

- cAdvisor (collect Docker statistics)
- [Prom. Node Exporter](https://github.com/prometheus/node_exporter) (collect executer statistics)
- re-use Suricata Exporter build for P4 demo a while ago?

---

## Usage:

Usage is documented [here](https://github.com/sonata-nfv/tng-sdk-benchmark/tree/master/prometheus)

**Comment by efotopoulou** [comment]
Hi again!
Seems i am converting to a big fan of tng-sdk-benchmark tool!
Let's see how the result of a set of benchmark experiments can be exposed to Prometheus.
Seems like `result_ts_metrics.csv` is the candidate info to be exported to a Prometheus instance.
That way will be easily visualized, queried and further analyzed from third party components such as tng-graph-profiler.

There are many client libs that tng-sdk-benchmark can adopt as seen here: [Prometheus client libraries](https://prometheus.io/docs/instrumenting/clientlibs/ ) so as to expose the experiment results.

Regarding the metrics naming, Prometheus suggests some good practices: [Best Practicies - metric and label naming](https://prometheus.io/docs/practices/naming/) that we should also take under consideration.

From the tng-graph-profiler side (still under development) the only important requirement is to understand the difference between experiments (if i have understand correctly the whole benchmarking process logic). Including the name of the function (as defined at ped)  or the experiment id as a part of the prometheus metric name should be enough.   What do you think?

By the way, where do you define the yaml schema of the PED (profiling experiment descriptor) ?
I can not find at [tng-schema](https://github.com/sonata-nfv/tng-schema) 

Thanks in advance :-)

**Comment by mpeuster** [comment]
Hi @efotopoulou ...

thanks for the great inputs! You are right the `result_ts_metrics.csv` stuff is the candidate for prometheus.

I need to add a Prometheus DB to the smart manufacturing pilot in the next days, so I have to work with it anyway.  I plan to also work on the exporter for tng-sdk-bench then. With your infos and best practices I am all set, I think. I will come back if I have further questions; or inform you once I am done. Plan is before next F2F :-)

Unfortunately there is no schema for the PED files yet. ... They have been a matter of many changes during the development of the tool (since 2017 already :-D)). But it is on the agenda to provide a schema for it sooner or later. But before that I want to first create a series of example experiments because I think this is much more helpful for the community.

This will be done as part of our work on the IETF draft (https://datatracker.ietf.org/doc/draft-rosa-bmwg-vnfbench/) for which "tng-bench" is one of the reference implementations.

**Comment by efotopoulou** [comment]
Great news @mpeuster ! I see your work is well-consolidated!
Please let me know when the experiment timeseries will be available at Prometheus. It would be really helpful for us to access with them before next F2F so as to show up also a demo of the profiler component. Since the profiler component already connects to a prometheus instance and is able to apply a set of analytic  services upon the pulled time series, i think that the integration with the benchmark component will be trivial. Let me know if you need any extra testing or feedback from our side :-)
