### ISSUE TITLE
Calibrate and verify application of resource limits

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-benchmark#59]
Check if resource limits are applied correctly! We use a stress service for this. 

Run: `tng-bench -p examples/peds/ped_calibration_stress.yml -v --hold`

|| mn.vnf0.vdu01 | mp.input | mp.output
| --- | --- |  --- |  --- |
| cput_t / cpu_set | OK / OK | OK / OK | OK / OK |
| cput_t / none | OK / OK  | OK / OK | OK / OK |
| none / cpu_set | OK / OK | OK / OK | OK / OK |
| memory | OK | OK | OK |
| memory_swap | MISS | MISS | MISS |
| io | MISS | MISS | MISS |
| ... | | | |

### TODOs

- [x] BUG cpupset ignored
  - Note: Containernet expects: `cpuset_cpus` as a string
  - [x] change tango.py to accept any input and convert to correct target format
  - [x] change emulator to forward value correctly from llcm to docker
  - [x] merge emulator changes
- [x] create a wiki page to document PED stuff, like  experiment_parameters 
  - [x] link this wiki page from ALL example PED (this repo and vnf-bench.model repo)
  - [x] update all PEDs with new format (als in vnf-bench-model)
- [ ] io_bw and mem_swap are still missing
- [ ] create a real multi config experiment (which tests the complete table) and run it
  - [ ] analyse the results (use for paper or at least for next deliverable!)
