### ISSUE TITLE
Enable memory_swap and io limits on vim-emu experimentation platforms

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-benchmark#68]
Check if resource limits are applied correctly! We use a stress service for this. 

Run: `tng-bench -p examples/peds/ped_calibration_stress.yml -v --hold`

|| mn.vnf0.vdu01 | mp.input | mp.output
| --- | --- |  --- |  --- |
| cput_t / cpu_set | OK / OK | OK / OK | OK / OK |
| cput_t / none | OK / OK  | OK / OK | OK / OK |
| none / cpu_set | OK / OK | OK / OK | OK / OK |
| memory | OK | OK | OK |
| memory_swap | MISS | MISS | MISS |
| io | MISS | MISS | MISS |
| ... | | | |

### TODOs

- [ ] io_bw and mem_swap are still missing
- [ ] create a real multi config experiment (which tests the complete table) and run it
  - [ ] analyse the results (use for paper or at least for next deliverable!)

### Old issue fixing the CPU stuff: #59
