### ISSUE TITLE
Create a YANG-based data model for PED files

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-benchmark#73]
Use a YANG model to have a clear schema for the PED files. This can also serve as input to IETF work.

Developments: https://github.com/mpeuster/tng-sdk-benchmark/blob/feature-73/models/

## YANG background

- [Wikipedia](https://en.wikipedia.org/wiki/YANG) (lots of useful pointers to RFCs etc.)
- [RFC7950 YANG Data Modeling Language](https://tools.ietf.org/html/rfc7950)
- https://blogs.cisco.com/getyourbuildon/yang-opensource-tools-for-data-modeling-driven-management
- https://wiki.onosproject.org/display/ONOS/YANG+Tools
- https://whatis.techtarget.com/definition/YANG-data-modeling-language
- [YANG for Dummies](https://napalm-automation.net/yang-for-dummies/)
- [Learning YANG](http://blog.devopssimplified.com/Learning_YANG)

## Examples

- [OSM IM](https://osm.etsi.org/gitweb/?p=osm/IM.git;a=tree;f=models/yang;h=36fb92cf769302f736fdafabdde50a87bfa0f18b;hb=HEAD)

## Tooling

Custom toolchain called from `Makefile`.

The toolchain automatically generates different model documentations in `doc/` (txt tree, html tree, uml). It also generates the Python model (`ietf_ped_model.py`) and finally it checks the example PEDs (`*.yaml`) against this model by loading them into the model.

Requirements:
- `pip install pyang pyangbind`
- `pyang` also needs to be install system wide to have correct paths to schema artefacts in system dirs

Call:
```sh
# validate model, build model, and test examples
make

# single targets
make validate # validate the model against ietf rules
make build # generate the python code model
make test # test the example PED files against model
```

## TODOs Toolchain

- [x] setup tooling (editor, pyang generation, documentation in README)
- [x] create `models` folder in repo
- [x] initial model to play with https://github.com/mpeuster/tng-sdk-benchmark/blob/feature-73/models/ped.yang
- [x] tool to validate PED file (*.yml) against YANG model: Custom build
- [ ] Jenkins integration (can we also trigger tests etc. with pytest? tox?)
- [ ] Problem: `mandatory` fields are not mandatory in validation (ignore this for now)
- [ ] ...

## TODOs Model
- [x] complete model
- [x] be more specific with units like CIDRs for addresses
- [x] be more specific in many of the `string` types. See `pattern` keyword.

## TODO Implementation
- [ ] make should place generated model to the right place in the source tree
- [ ] update implementation to support new model

## Goal
Replace all legacy interactions with the PED model inside tng-sdk-bench with a `pyang`/`pybind` based solution using generated Python code.

**Comment by mpeuster** [comment]
First working toolchain


```sh
# validate model and build python model
make
# test the model agains a yaml
make test
```

**Comment by mpeuster** [comment]
Status: Model is finished so far (at least we should be able to express everything we expressed before).

Next step: Implementation in code!
